# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-08 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('idUser', models.AutoField(primary_key=True, serialize=False)),
                ('nameUser', models.CharField(max_length=50)),
                ('emailUser', models.CharField(max_length=50)),
            ],
        ),
    ]
